### ISSUE TITLE
Breaking the git linkage

### ISSUE THREAD

**Issue by libdefi** [dabit3/react-native-ai#2]
When I used `npx rn-ai` to create a test app and attempt to upload it to my Github, which means it has been linked to your repo.

I could fix it manually and upload it, but it's a little stressful and you might as well fix it.

Thanks.

**Comment by dabit3** [comment]
try `rm -rf .git` after creating a new project and it should let you create a new git configuration using `git init`

**Comment by dabit3** [comment]
@libdefi actually updated the CLI to do this automatically
