### ISSUE TITLE
TypeError: Cannot read property 'backgroundColor' of undefined

### ISSUE THREAD

**Issue by nirlepadhikari** [dabit3/react-native-ai#3]
--------------------------------
This error is located at:
    in MainComponent (created by Main)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Main)
    in Main (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in RCTView (created by View)
    in View (at CustomActionSheet.tsx:91)
    in RCTView (created by View)
    in View (at CustomActionSheet.tsx:99)
    in CustomActionSheet (at ActionSheetProvider.tsx:49)
    in ActionSheetProvider (created by App)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
------------------------------

The same template was working a few days ago. Today when I started a new project with 'npx rn-ai' and started the expo server, I got the above error.

**Comment by dabit3** [comment]
Hey, may need to delete and re-install expo, sounds like a custom theme was save to local-storage and not available in the new build.

**Comment by dabit3** [comment]
Will push a fix to handle the error though.
